[build]
  command = "npm run build"
  publish = ".next"

  [[redirects]] 
  from = "deal" 
  to = "https://ludvio.systeme.io/e4f32e55" 
  status = 301

  [build.environment]
    # cache Cypress binary in local "node_modules" folder
    # so Netlify caches it
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    # set TERM variable for terminal output
    TERM = "xterm"

[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
      record = true
      group = "Testing Built Site"
